apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploymentName }}-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.deploymentName }}
  template:
    metadata:
      labels:
        app: {{ .Values.deploymentName }}
    spec:
      containers:
        - name: {{ .Values.deploymentName }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config-volume
              mountPath: /app/application.properties
              subPath: application.properties
            - name: service-volume
              mountPath: /app/services.json
              subPath: services.json
            - name: tmp-volume
              mountPath: /tmp
          command: ["java"]
          args: ["-Djava.security.egd=file:/dev/./urandom", "-jar", "/app/eurekaclient.jar"]
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Values.deploymentName }}-config
        - name: service-volume
          configMap:
            name: {{ .Values.deploymentName }}-service
        - name: tmp-volume
          emptyDir: {}
