apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deploymentName }}-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.deploymentName }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
