replicaCount: 1
hostName: eurekaclient.tp.lan
deploymentName: eurekaclient
namespace: eureka
gateWayNamespace: istio-ingress

image:
  repository: wlanboy/eurekaclientjava
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

certmanager:
  issuer: local-ca-issuer
  kind: ClusterIssuer
  secretName: eurekaclientjava-tls

resources: {}
