replicaCount: 1
hosts: 
  - eurekaclient.tp.lan
  - eurekaclient.gmk.lan
deploymentName: eurekaclient
namespace: eureka
gateWayNamespace: istio-ingress

image:
  repository: wlanboy/eurekaclientjava
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

certmanager:
  issuer: local-ca-issuer
  kind: ClusterIssuer
  secretName: eurekaclient-tls

resources: {}
